ruby:
  image: ruby:2.2.3
  environment:
    mongo_db_host: db
    GEM_PATH: /usr/src/app/vendor/bundle/ruby/2.2.0:/root/.gem/ruby/2.2.0:/usr/local/lib/ruby/gems/2.2.0:/usr/local/bundle
  working_dir: /usr/src/app
  volumes:
    - .:/usr/src/app
  command: bundle exec ./vendor/bundle/ruby/2.2.0/bin/rackup --host 0.0.0.0 -p 80 -s thin
  ports:
    - "80:80"

db:
  image: mongo:3.1.8
